solitaire: main.o deal_cards.o random.o modulo.o print_array.o zero_element.o check_complete.o
	gcc -o solitaire main.o deal_cards.o random.o modulo.o print_array.o zero_element.o check_complete.o

main.o: main.s
	gcc -c -g main.s

deal_cards.o: deal_cards.s
	gcc -c -g deal_cards.s

random.o: random.s
	gcc -c -g random.s

modulo.o: modulo.s
	gcc -c -g modulo.s

print_array.o: print_array.s
	gcc -c -g print_array.s

zero_element.o: zero_element.s
	gcc -c -g zero_element.s

check_complete.o: check_complete.s
	gcc -c -g check_complete.s

